[versions]
activity = "1.9.2"
agp = "8.8.0-alpha07"
annotation = "1.8.2"
appcompat = "1.7.0"
coil = "2.7.0"
collapsingtoolbarlayout-subtitle = "1.5.0"
collection = "1.4.4"
constraintlayout = "2.2.0-beta01"
coordinatorlayout = "1.3.0-alpha02"
customview = "1.2.0-alpha02"
documentfile = "1.1.0-alpha01"
draganddrop = "1.0.0"
drawer = "1.0.3"
drawerlayout = "1.2.0"
dynamicanimation = "1.1.0-alpha03"
emoji2 = "1.5.0"
fragment = "1.8.4"
gridlayout = "1.1.0-beta01"
kotlin = "2.0.20"
core-ktx = "1.13.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
legacy-support-core-utils = "1.0.0"
library = "1.3.0"
lifecycle-runtime = "2.8.6"
lottie = "6.4.1"
material = "1.12.0"
navigation = "2.8.2"
okhttp = "4.12.0"
palette = "1.0.0"
preference = "1.2.1"
recyclerview = "1.3.2"
recyclerview-animators = "4.0.2"
startup-runtime = "1.2.0"
swiperefreshlayout = "1.2.0-alpha01"
transition = "1.5.1"
viewpager = "1.1.0-alpha01"
viewpager2 = "1.1.0"
window = "1.3.0"
zip4j = "2.11.5"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "collection" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
androidx-customview = { module = "androidx.customview:customview", version.ref = "customview" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-draganddrop = { module = "androidx.draganddrop:draganddrop", version.ref = "draganddrop" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
androidx-emoji2 = { module = "androidx.emoji2:emoji2", version.ref = "emoji2" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
androidx-legacy-support-core-ui = { module = "androidx.legacy:legacy-support-core-ui", version.ref = "legacy-support-core-utils" }
androidx-legacy-support-core-utils = { module = "androidx.legacy:legacy-support-core-utils", version.ref = "legacy-support-core-utils" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle-runtime" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-runtime" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle-runtime" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "palette" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
androidx-transition = { module = "androidx.transition:transition", version.ref = "transition" }
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
collapsingtoolbarlayout-subtitle = { module = "com.hendraanggrian.material:collapsingtoolbarlayout-subtitle", version.ref = "collapsingtoolbarlayout-subtitle" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
drawer = { module = "com.drakeet.drawer:drawer", version.ref = "drawer" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
library = { module = "me.zhanghai.android.fastscroll:library", version.ref = "library" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
recyclerview-animators = { module = "jp.wasabeef:recyclerview-animators", version.ref = "recyclerview-animators" }
zip4j = { module = "net.lingala.zip4j:zip4j", version.ref = "zip4j" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

